{%- set merged_python_version = cookiecutter.minimal_python_version.replace('.', '') -%}

default_stages: [commit, push]

repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: trailing-whitespace
        exclude: ^exports/
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=100"]
        exclude: |
          (?x)^(
            ^exports/|
            ^poetry.lock
          )$
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system
{% if cookiecutter.vcs_remote_type != 'none' %}
      - id: git-commit-prefix
        name: git-commit-prefix{% if cookiecutter.vcs_remote_type == 'bitbucket' %}
        entry: poetry run python .additional/bitbucket_commit_prefix.py{% elif cookiecutter.vcs_remote_type == 'github' %}
        entry: poetry run python .additional/github_commit_prefix.py{% endif %}
        language: python
        stages: [prepare-commit-msg]
        description: Searches the branch name for something looking like an issue name template and prepends the commit message with it{% endif %}

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout{% if cookiecutter.include_mypy_linter == 'y' %}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy{% endif %}
