# This file contains values from Cookiecutter

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  project_slug: "{{ cookiecutter.project_slug }}"
  project_description: "{{ cookiecutter.project_description }}"
  username: "{{ cookiecutter.username }}"
  email: "{{ cookiecutter.email }}"
  vcs_remote_type: "{{ cookiecutter.vcs_remote_type   }}"
  minimal_python_version: "{{ cookiecutter.minimal_python_version }}"
  version: "{{ cookiecutter.version }}"
  line_length: "{{ cookiecutter.line_length }}"

  python_linter: "{{ cookiecutter.python_linter }}"
  python_formatter: "{{ cookiecutter.python_formatter }}"

  include_mypy_type_checker: "{{ cookiecutter.include_mypy_type_checker }}"
  include_cli_example: "{{ cookiecutter.include_cli_example }}"
  include_docker_sample: "{{ cookiecutter.include_docker_sample }}"
  include_tests_sample: "{{ cookiecutter.include_tests_sample }}"
  include_notebooks_sample: "{{ cookiecutter.include_notebooks_sample }}"
