default_stages:
- pre-commit
- pre-push
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        exclude: ^{{ cookiecutter.project_name }}
    -   id: check-toml
        exclude: ^{{ cookiecutter.project_name }}
    -   id: check-json
    -   id: end-of-file-fixer
        exclude: ^LICENSE
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args:
        - --fix=lf
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-added-large-files
        args:
        - --maxkb=100

-   repo: local
    hooks:
    -   id: generate-samples
        name: Generate project samples
        entry: poetry run bash scripts/generate_sample_projects.sh
        language: system

    -   id: git-commit-prefix
        name: git-commit-prefix
        entry: poetry run python .additional/github_commit_prefix.py
        language: python
        stages: [prepare-commit-msg]
        description: Searches the branch name for something looking like an issue name template and prepends the commit message with it
