# This file contains values from Cookiecutter

default_context:
  project_name: "poetry-project-mypy-wemake-black"
  project_slug: "poetry_project_mypy_wemake_black"
  project_description: "Awesome `poetry-project-mypy-wemake-black` project!"
  username: "Awesome user"
  email: "awesome-user@example.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.12"
  version: "0.1.0"
  line_length: "100"
  package_manager: "poetry"

  python_linter: "wemake"
  python_formatter: "black"
  python_type_checker: "mypy"

  include_cli_example: "n"
  include_docker_sample: "y"
  include_notebooks_sample: "y"
