# This file contains values from Cookiecutter

default_context:
  project_name: "poetry-project-ty-ruff"
  project_slug: "poetry_project_ty_ruff"
  project_description: "Awesome `poetry-project-ty-ruff` project!"
  username: "Awesome user"
  email: "awesome-user@example.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.12"
  version: "0.1.0"
  line_length: "120"
  package_manager: "poetry"

  python_linter: "ruff"
  python_formatter: "ruff"
  python_type_checker: "ty"

  include_cli_example: "n"
  include_docker_sample: "y"
  include_notebooks_sample: "y"
