name: Test project creation

on:
  push:
  workflow_dispatch:

jobs:
  test-project-311-poetry-180-docker-bitbucket:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py311
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py311-poetry-docker-bitbucket.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-39-poetry-185-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py39
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py39-poetry-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-39-poetry-183-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py39
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py39-poetry-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-310-poetry-184-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py310
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py310-poetry-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-310-poetry-mypy-180-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py310
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py310-poetry-mypy-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-310-poetry-mypy-180-docker-github-ruff:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py310
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py310-poetry-mypy-docker-github-ruff.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-311-poetry-180-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py311
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py311-poetry-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project

  test-project-312-poetry-180-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter/py312
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Setup base project
        run: make project-init-ci

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/py312-poetry-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project
