name: Test project creation

on:
  push:
  workflow_dispatch:

jobs:
  test-project-poetry-docker-github:
    runs-on: ubuntu-latest
    env:
      new_project_directory: /tmp/cookiecutter
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4git c.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: poetry

      - name: Setup base project
        run: make project-init

      - name: Create project from template
        run: poetry run cookiecutter . -f --config-file test-configs/poetry-docker-github.yaml --no-input -o $new_project_directory

      - name: Test project commands
        run: bash scripts/test_project_poetry.sh $new_project_directory/test-project
